### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/gerrit/server/OutputFormat

### ISSUE THREAD

**Issue by dhowden** [davido/gerrit-oauth-provider#114]
Getting this error (which is preventing token refreshes) when trying to use the plugin with the latest master build of gerrit (2.16.2-853-ga9064ca785).

**Comment by mwebber** [comment]
If the problem is in the delete-project plugin, can I suggest posting a question on the Gerrit forum (https://groups.google.com/forum/#!forum/repo-discuss)? Make sure you include the exact versions of both Gerrit and the delete-project plugin.
I think (not sure) I saw some earlier messages there about delete-project not having being updated for 2.16, but I'm not sure of the details or current status.

**Comment by dhowden** [comment]
The problem is in this codebase, I was referencing that change to the `delete-project` plugin to show the solution.

Here is the full trace from the error:

```
java.lang.NoClassDefFoundError: com/google/gerrit/server/OutputFormat
	at com.googlesource.gerrit.plugins.oauth.GoogleOAuthService.getUserInfo(GoogleOAuthService.java:109)
	at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:106)
	at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:105)
	at com.google.gerrit.httpd.RequireSslFilter.doFilter(RequireSslFilter.java:72)
	at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:121)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:133)
	at com.googlesource.gerrit.plugins.loginredirect.LoginRedirectFilter.doFilter(LoginRedirectFilter.java:53)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:129)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:135)
	at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:57)
	at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:69)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by davido** [comment]
Yes, this was changed on master: [1]. The last released version of this plugin should be compatible with gerrit 2.15 plugin API and all 2.16 releases. It seems, that you are running gerrit@HEAD? Wau, respect! ;-)

* [1] https://gerrit-review.googlesource.com/c/gerrit/+/208043

**Comment by adamyi** [comment]
I'm running HEAD and can confirm that this issue still exists. Will try to fix it.

**Comment by adamyi** [comment]
Oops sorry. Seems that the github master is not synced with upstream.

**Comment by vivekchauhan** [comment]
I am seeing this error after upgrading to Gerrit 3.0 Release and version 2.16.1 of Gerrit OAuth Provider Plugin.

**Comment by vivekchauhan** [comment]
The packages have been refactored due to which this class is not available.

For the time being, I have downloaded the master jar from https://gerrit-ci.gerritforge.com/job/plugin-oauth-bazel-master/35/ and replaced with v2.16.1  to make the authentication work.

**Comment by davido** [comment]
Yes, sorry for the mess.

**Comment by romanharen1** [comment]
So, this plugin doesnt work with gerrit version older than 2.16?
i try to use the last plugin version in gerrit 2.11.3 and i got this error.

**Comment by andersoxie** [comment]
I get  a similar error but do not have the delete-project installed. I am running:

[2020-07-28T08:52:00.132+0200] [main] INFO  com.google.gerrit.pgm.Daemon : Gerrit Code Review 3.2.2 ready


java.lang.NoClassDefFoundError: com/google/gerrit/server/OutputFormat
        at com.googlesource.gerrit.plugins.oauth.GitHubOAuthService.getUserInfo(GitHubOAuthService.java:86)
        at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:105)
        at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:105)
        at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:120)
        at com.google.gerrit.httpd.SetThreadNameFilter.doFilter(SetThreadNameFilter.java:62)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:139)
        at com.google.gerrit.httpd.AllowRenderInFrameFilter.doFilter(AllowRenderInFrameFilter.java:56)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:135)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:141)
        at com.google.gerrit.httpd.RequestCleanupFilter.doFilter(RequestCleanupFilter.java:60)
        at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:57)
        at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:64)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:500)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)

**Comment by davido** [comment]
@andersoxie Can you try with latest plugin downloaded from GeritForge CI: [1]?

I really should conduct new release and upload it to GitHub project release page. Sorry for the troubles.

[1] https://gerrit-ci.gerritforge.com/view/Plugins-stable-3.2/job/plugin-oauth-bazel-master-stable-3.2/20/artifact/bazel-bin/plugins/oauth/oauth.jar

**Comment by paulfertser** [comment]
Hello Davido,
We (OpenOCD) migrated to Gerrit 3.4.0 from Gerrit 2.13.6 today. Google OAuth is considered essential for our contributors so I downloaded https://gerrit-ci.gerritforge.com/view/Plugins-stable-3.3/job/plugin-oauth-bazel-master-stable-3.3/lastSuccessfulBuild/artifact/bazel-bin/plugins/oauth/oauth.jar (just the latest for today) and confirm it works on our "production" at least for Google OAuth and Github without any issues.
Your plugin is such an essential part of Gerrit functionality for free software projects, thanks a lot for working on it! Probably you can consider releasing a new version soon please? Or ask on Gerrit mailing list if anyone's willing to co-maintain probably?

**Comment by davido** [comment]
> Your plugin is such an essential part of Gerrit functionality for free software projects, thanks a lot for working on it!

Thanks for the feedback!

Note, though, that this and other gerrit plugins have received **a lot** of feedback and contribution from the whole gerrit community.

So may be share your feedback on the [gerrit mailing list](https://groups.google.com/g/repo-discuss/), like @grandinj did recently in this [post](https://groups.google.com/g/repo-discuss/c/Q8KLJ_6YplM).

> Probably you can consider releasing a new version soon please? Or ask on Gerrit mailing list if anyone's willing to co-maintain probably?

Right, this is on my list. (Currently I'm quite busy with my $DAY_JOB.)
